Repository telekom-mms/ansible-collection-acme, pull requests merged in 2020-12, with the labels that each got.

#17 remove letsencrypt_create_private_keys variable from examples
  examples/SAN_example.com.yml
  examples/wildcard.example.com.yml
  examples/www.example.com.yml
Labels: documentation

#22 Add Hetzner DNS as letsencrypt_dns_provider
  examples/wildcard.example.com.yml
  roles/letsencrypt/tasks/dns-challenge-hetzner.yml
  roles/letsencrypt/tasks/dns-challenge.yml
Labels: enhancement

#21 fix broken AutoDNS wildcard creation #20
  roles/letsencrypt/tasks/dns-challenge-autodns.yml
Labels: bug

#27 adjust variable naming in example files and readme
  examples/SAN_example.com.yml
  examples/www.example.com.yml
  roles/letsencrypt/README.md
Labels: documentation
