Repository telekom-mms/ansible-collection-acme, pull requests merged in 2021-01, with the labels that each got.

#28 update documentation
  roles/letsencrypt/README.md
Labels: documentation

#31 Feature / dns challenge otc openstack
  galaxy.yml
  roles/letsencrypt/README.md
  roles/letsencrypt/defaults/main.yml
  roles/letsencrypt/tasks/dns-challenge-openstack.yml
  roles/letsencrypt/tasks/dns-challenge.yml
Labels: enhancement, minor

#33 Account key content as variable
  roles/letsencrypt/README.md
  roles/letsencrypt/tasks/create-keys.yml
Labels: enhancement, minor

#35 unify challenge provider logic
  roles/letsencrypt/defaults/main.yml
  roles/letsencrypt/tasks/challenge-unknown.yml
  roles/letsencrypt/tasks/dns-challenge.yml
  roles/letsencrypt/tasks/dns-challenge/autodns.yml
  roles/letsencrypt/tasks/dns-challenge/azure.yml
  roles/letsencrypt/tasks/dns-challenge/hetzner.yml
  roles/letsencrypt/tasks/dns-challenge/openstack.yml
  roles/letsencrypt/tasks/dns-challenge/pebble.yml
  roles/letsencrypt/tasks/http-challenge.yml
  roles/letsencrypt/tasks/http-challenge/s3.yml
  roles/letsencrypt/tasks/letsencrypt_preconditions.yml
  roles/letsencrypt/tasks/main.yml
  roles/letsencrypt/tasks/preconditions.yml
Labels: enhancement, patch
